bottenderjs/bottenderjs.github.io

content/docs/Platforms-Messenger.md
=> Add options in messenger doc

content/docs/APIReference-Context.md, content/docs/Platforms-Messenger.md
https://github.com/Yoctol/bottender/releases/tag/v0.14.3
=> update docs for bottender 0.14.3

content/docs/Guides-Server.md, content/docs/Guides-Session.md
https://github.com/Yoctol/bottender/pull/34
=> Rename some examples url

content/docs/APIReference-Context.md
We don't recommend it any more.
=> Removed sendQuickReplies in the docs

content/docs/Guides-Session.md
See https://github.com/Yoctol/bottender/blob/master/src/session/MongoSessionStore.js#L39
=> SessionStore expiration unit is minutes

content/docs/Guides-Troubleshooting.md, content/docs/nav.yaml
=> add troubleshooting guide

content/docs/APIReference-LineContext.md, content/docs/nav.yaml
to be implemented:
- context.getUserProfile
- context.getMemberProfile?
+ context.getGroupMemberProfile?
+ context.getRoomMemberProfile?
- getMemberIds?
+ getGroupMemberIds
+ getRoomMemberIds
- getAllMemberIds?
+ getAllGroupMemberIds
+ getAllRoomMemberIds
=> add APIReference-LineContext

content/docs/APIReference-ViberContext.md
Should be merged after releasing https://github.com/Yoctol/bottender/pull/210
=> enable Viber getUserDetails, getOnlineStatus docs

content/docs/APIReference-Event.md
Drop event table and put platform specific docs instead.
=> rewrite event api doc

src/components/Footer.js, src/components/Header.js, src/components/ListItem.js, src/components/ListSection.js, src/components/Nav.js, src/components/NavItem.js, src/components/home/ExhibitionSection.js, src/components/home/IntroductionSection.js, src/css/index.js, src/layouts/index.js, src/layouts/sidebar-layout.js, src/templates/withSidebar.js, src/utils/typography.js
=> Rewrite CSS Style

gatsby-node.js, src/components/Header.js, src/components/Nav.js, src/layouts/index.js, src/layouts/sidebar-layout.js
Should fix broken blog path on production.
=> Fix broken blog path

src/components/EditThisPage.js, src/components/Footer.js, src/components/ListItem.js, src/components/MobileMenu.js, src/components/Nav.js, src/components/SearchBar.js, src/components/home/CTASection.js, src/components/home/ExhibitionItem.js, src/components/home/ExhibitionSection.js, src/components/home/IntroductionItem.js, src/components/home/IntroductionSection.js, src/components/home/LandscapeSection.js
Fix mobile-menu and use as many stateless functional component as possible.
=> Functional component

src/components/home/LandscapeSection.js, src/layouts/head.js, src/layouts/index.js, src/layouts/sidebar-layout.js
https://github.com/Yoctol/bottender/issues/228
=> Flexibly -> Flexible

content/docs/Guides-Troubleshooting.md
https://github.com/Yoctol/bottender/pull/295
=> change debug keys doc

content/docs/APIReference-MessengerEvent.md
https://github.com/Yoctol/bottender/pull/268
=> Update brandedCamera method on Messenger event

content/docs/APIReference-MessengerEvent.md, yarn.lock
https://github.com/Yoctol/bottender/pull/266
=> Add game_play event on messenger

content/docs/APIReference-LineContext.md
1. function name : reply -> replyText
2. remove Content API
=> edit function name & remove useless link

content/docs/GettingStarted.md
=> better screenshots

content/docs/APIReference-LineContext.md
Follow up from:
https://github.com/Yoctol/messaging-apis/pull/381
=> add documentation for flex methods

content/authors.yaml, package.json, src/templates/withSidebar.js, yarn.lock
=> add author image and time-ago

content/authors.yaml
try now Automatic Deployments for Pull Requests
=> add author wtflink

content/docs/GettingStarted.md
Change `bot.handle()` to `bot.onEvent()` async method.
=> Update bot method on Getting started guide

content/blog/2018-08-03-bottender-0_15.md
=> fix image format

src/components/ListSection.js, src/components/Sidebar.js
=> put latest blog post on top of sidemenu

content/docs/Guides-Session.md
```js
// @flow
class Store implements SessionStore {
init(): Promise<SessionStore> {
/* Initializes the session store */
}
read(sessionId: string): Promise<Session | null> {
/* Reads single session from the session store  */
}
write(sessionId: string, data): Promise<void> {
/* Writes single session to the session store  */
}
destroy(sessionId: string): Promise<void> {
/* Deletes single session from the session store  */
}
all(): Promise<Array<Session>> {
/* Reads all sessions from the session store  */
}
}
```
=> add docs for SessionStore.all
